replicaCount: 1

hostNetwork: false

updateStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0

image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent

service:
#  type: NodePort
  type: LoadBalancer
  externalPort: 443
  internalPort: 443
  externalIPs: []
#  nodePort: 30443
#  annotations:
#    metallb.universe.tf/address-pool: system

podAnnotations: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
#  storageClass: hostpath
#  accessMode: ReadWriteOnce
#  size: 128Mi

openvpn:
#  OVPN_NETWORK: "192.168.249.0/24"
#  OVPN_PROTO: tcp
#  OVPN_K8S_POD_NETWORK: "10.11.0.0/16"
#  OVPN_K8S_SVC_NETWORK: "10.241.0.0/16"

  dhcpOptionDomain: true
  redirectGateway: false

  # Arbitrary lines appended to the end of the server configuration file
  # conf: |
  #  max-clients 100
  #  client-to-client

nodeSelector: {}
